name: tiny_trans
channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - cpuonly

  - pip:
      - transformers==4.35.2
      - numpy<2
      - tqdm
